# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# Chạy các task song song để tận dụng tối đa CPU
org.gradle.parallel=true

# Bật Build Cache để tái sử dụng các kết quả biên dịch trước đó
org.gradle.caching=true

# Bật Configuration Cache giúp bỏ qua bước cấu hình khi không có thay đổi build script
org.gradle.configuration-cache=true

# Bật tính năng biên dịch gia tăng cho Kotlin và KSP
kotlin.incremental=true
ksp.incremental=true

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Tối ưu hóa Kotlin Daemon
kotlin.daemon.jvm.options=-Xmx2048m

# Giảm kích thước file R, giúp tăng tốc build resource
android.nonTransitiveRClass=true
